import { escapeHtml, textList } from '../utils/safe.js';

const score = (label, value) => `<div class="rounded-xl border border-slate-200 bg-slate-50 p-3 text-center"><dt class="text-[10px] font-bold uppercase text-slate-500">${label}</dt><dd class="mt-1 text-lg font-extrabold text-brand-600">${escapeHtml(value)}/100</dd></div>`;
const status = (operation) => `<p class="mt-4 text-sm" role="status">${operation.loading ? 'Working with your project context…' : escapeHtml(operation.error || '')}</p>`;
const ResourcesView = stack => { const joined=(stack||[]).join(' ').toLowerCase(); const topics=['Programming fundamentals and Git','HTTP, REST APIs, and authentication']; if(/react|vue|angular|tailwind|css/.test(joined)) topics.push('Responsive UI, accessibility, and component design'); if(/python|node|fastapi|django|express/.test(joined)) topics.push('Backend architecture, validation, and error handling'); if(/sql|mongo|postgres|database/.test(joined)) topics.push('Database modeling, indexes, and migrations'); if(/gemini|ai|machine|ml/.test(joined)) topics.push('Prompt design, AI safety, and evaluation'); topics.push('Deployment fundamentals, environment variables, and monitoring'); return `<section class="rounded-2xl bg-white p-5 border border-slate-200"><h2 class="font-bold">Prerequisites to learn</h2><p class="mt-1 text-xs text-slate-500">Search these topics in the official documentation or a course platform you trust.</p>${textList(topics)}</section>`; };

export const ProjectDetailsView = ({ project, saved, compared, evaluation, blueprint, improvement, operations, roadmap }) => {
  if (!project) return `<section class="pt-28 max-w-3xl mx-auto px-4"><h1 class="text-2xl font-bold">Project not found</h1><a class="text-brand-600" href="#results">Return to recommendations</a></section>`;
  const p = project;
  const blueprintOperation = operations?.blueprint || {};
  return `<section class="pt-24 pb-16"><div class="max-w-6xl mx-auto px-4 sm:px-6"><a href="#results" class="text-sm font-semibold text-brand-600">← Recommendations</a><header class="mt-4 rounded-3xl bg-slate-900 p-6 sm:p-9 text-white"><p class="text-sm text-brand-300">${escapeHtml(p.domain)} · ${escapeHtml(p.difficulty)}</p><h1 class="mt-2 text-3xl font-extrabold">${escapeHtml(p.title)}</h1><p class="mt-3 max-w-3xl text-slate-300">${escapeHtml(p.shortDescription)}</p><div class="mt-6 flex flex-wrap gap-3"><button type="button" onclick="window.runEvaluation()" class="rounded-xl bg-brand-500 px-4 py-2 font-bold text-white">Evaluate Project</button><button type="button" onclick="window.runBlueprint()" ${blueprintOperation.loading ? 'disabled aria-disabled="true"' : ''} class="rounded-xl bg-white px-4 py-2 font-bold text-slate-900 disabled:cursor-not-allowed disabled:opacity-60">${blueprintOperation.loading ? 'Building blueprint…' : 'Build This Project'}</button><button type="button" onclick="window.openPresentation()" class="rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white hover:bg-indigo-700">Generate Presentation</button><button type="button" onclick="window.openViva()" class="rounded-xl bg-purple-600 px-4 py-2 font-bold text-white hover:bg-purple-700">Prepare for Viva</button><button type="button" onclick="window.showImprove()" class="rounded-xl border border-slate-500 px-4 py-2 font-bold">Improve This Project</button><button type="button" onclick="window.toggleSaveCurrent()" class="rounded-xl border border-slate-500 px-4 py-2">${saved ? 'Unsave' : 'Save Project'}</button><button type="button" onclick="window.toggleCompareCurrent()" class="rounded-xl border border-slate-500 px-4 py-2">${compared ? 'Remove from Compare' : 'Add to Compare'}</button></div>${blueprintOperation.loading ? '<p class="mt-4 text-sm text-brand-100" role="status">Creating your project blueprint…</p>' : ''}${blueprintOperation.error ? `<div class="mt-4 flex flex-wrap items-center gap-3 text-sm text-red-100" role="alert"><span>${escapeHtml(blueprintOperation.error)}</span><button type="button" onclick="window.runBlueprint()" class="rounded-lg border border-red-200 px-3 py-1 font-bold">Retry blueprint</button></div>` : ''}</header>
  <div class="mt-8 grid gap-6 lg:grid-cols-3"><article class="lg:col-span-2 space-y-6"><section class="rounded-2xl bg-white p-6 shadow-sm border border-slate-200"><h2 class="text-xl font-bold">Project details</h2><dl class="mt-4 space-y-4 text-sm"><div><dt class="font-bold">Problem statement</dt><dd>${escapeHtml(p.problemStatement)}</dd></div><div><dt class="font-bold">Why it fits you</dt><dd>${escapeHtml(p.whyItFits)}</dd></div><div><dt class="font-bold">Target users</dt><dd>${escapeHtml(p.targetUsers)}</dd></div><div><dt class="font-bold">Unique value</dt><dd>${escapeHtml(p.uniqueValue)}</dd></div><div><dt class="font-bold">Possible challenges</dt><dd>${textList(p.possibleChallenges)}</dd></div></dl></section>${evaluation ? EvaluationView(evaluation) : ''}${blueprint ? BlueprintView(blueprint) : ''}${roadmap ? RoadmapView(roadmap, p.id) : ''}${improvement ? ImprovementView(improvement) : ''}</article><aside class="space-y-6"><section class="rounded-2xl bg-white p-5 border border-slate-200"><h2 class="font-bold">Fit snapshot</h2><dl class="mt-4 grid grid-cols-2 gap-3">${score('Feasibility', p.feasibilityScore)}${score('Innovation', p.innovationScore)}${score('Final-year fit', p.finalYearSuitabilityScore)}<div class="rounded-xl border border-slate-200 p-3 text-center"><dt class="text-[10px] font-bold uppercase text-slate-500">Scope</dt><dd class="mt-1 text-sm font-bold">${escapeHtml(p.estimatedScope)}</dd></div></dl></section><section class="rounded-2xl bg-white p-5 border border-slate-200"><h2 class="font-bold">Technology stack</h2><div class="mt-3 flex flex-wrap gap-2">${p.techStack.map(x => `<span class="rounded-lg bg-slate-100 px-2 py-1 text-xs">${escapeHtml(x)}</span>`).join('')}</div><h2 class="mt-5 font-bold">Key features</h2>${textList(p.keyFeatures)}<button onclick="window.openMentor()" class="mt-5 w-full rounded-xl bg-slate-900 px-4 py-2 font-bold text-white">Open AI Mentor</button><button onclick="window.openPresentation()" class="mt-2 w-full rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white">Generate Presentation</button><button onclick="window.openViva()" class="mt-2 w-full rounded-xl bg-purple-600 px-4 py-2 font-bold text-white">Prepare for Viva</button></section>${ResourcesView(p.techStack)}</aside></div>
  <section id="improve-panel" class="mt-8 rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Improve this project</h2><label class="mt-3 block text-sm font-medium" for="improvement-concern">What concerns you?</label><textarea id="improvement-concern" class="mt-1 w-full rounded-xl border border-slate-300 p-3" maxlength="1000" placeholder="For example: This feels too difficult for a four-month individual project."></textarea><button onclick="window.runImprovement()" class="mt-3 rounded-xl bg-brand-600 px-4 py-2 font-bold text-white">Get improvement advice</button>${status(operations.improve)}</section>${status(operations.evaluate)}${status(operations.blueprint)}</div></section>`;
};

export const EvaluationView = e => `<section class="rounded-2xl border border-brand-200 bg-brand-50 p-6"><h2 class="text-xl font-bold">Project evaluation</h2><dl class="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">${score('Overall', e.overallScore)}${score('Feasibility', e.feasibilityScore)}${score('Innovation', e.innovationScore)}${score('Technical depth', e.technicalDepthScore)}${score('Final-year fit', e.finalYearSuitabilityScore)}${score('Scope fit', e.scopeFitScore)}</dl><div class="mt-5 grid gap-4 md:grid-cols-3"><div><h3 class="font-bold">Strengths</h3>${textList(e.strengths)}</div><div><h3 class="font-bold">Risks</h3>${textList(e.risks)}</div><div><h3 class="font-bold">Mitigation</h3>${textList(e.mitigation)}</div></div><p class="mt-5 rounded-xl bg-white p-4 text-sm"><b>Recommendation:</b> ${escapeHtml(e.recommendation)}</p></section>`;

export const BlueprintView = b => `<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Build blueprint</h2><div class="mt-4 space-y-4 text-sm"><p><b>Summary:</b> ${escapeHtml(b.projectSummary)}</p><p><b>Problem:</b> ${escapeHtml(b.problemDefinition)}</p><p><b>Solution:</b> ${escapeHtml(b.proposedSolution)}</p><p><b>Target users:</b> ${escapeHtml(b.targetUsers)}</p><div class="grid gap-4 md:grid-cols-2"><div><h3 class="font-bold">MVP / must have</h3>${textList(b.mvpFeatures)}</div><div><h3 class="font-bold">Optional / future</h3>${textList(b.optionalFeatures)}</div><div><h3 class="font-bold">Functional requirements</h3>${textList(b.functionalRequirements)}</div><div><h3 class="font-bold">Non-functional requirements</h3>${textList(b.nonFunctionalRequirements)}</div><div><h3 class="font-bold">Technology stack</h3>${textList(b.recommendedTechStack)}</div><div><h3 class="font-bold">Development phases</h3>${textList(b.developmentPhases)}</div><div><h3 class="font-bold">Risks and mitigations</h3>${textList(b.risksAndMitigations)}</div></div><p><b>Architecture:</b> ${escapeHtml(b.systemArchitecture)}</p><p><b>Database:</b> ${escapeHtml(b.databaseDesign)}</p><p><b>API design:</b> ${escapeHtml(b.apiPlan)}</p><p><b>AI integration:</b> ${escapeHtml(b.aiIntegrationPlan)}</p><p><b>Testing:</b> ${escapeHtml(b.testingStrategy)}</p><p><b>Deployment:</b> ${escapeHtml(b.deploymentPlan)}</p><p><b>Security:</b> ${escapeHtml(b.securityConsiderations)}</p><p><b>Future scope:</b> ${escapeHtml(b.futureScope)}</p></div></section>`;

export const RoadmapView = (roadmap, id) => { const tasks = roadmap.flatMap((phase, pi)=>phase.tasks.map((task, ti)=>({...task,pi,ti,phase:phase.name}))), done = tasks.filter(x=>x.done).length, next = tasks.find(x=>!x.done), total=tasks.length; return `<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-bold">Development roadmap</h2><p class="mt-1 text-sm" role="status">${done}/${total} tasks complete · ${total ? Math.round(done*100/total) : 0}% progress · Current phase: ${escapeHtml(next?.phase || 'Complete')}</p>${next ? `<div class="mt-3 rounded-xl bg-brand-50 p-3 text-sm"><b>Next recommended task:</b> ${escapeHtml(next.text)}<button onclick="window.continueBuilding()" class="ml-3 font-bold text-brand-700">Continue Building</button></div>` : ''}<div class="mt-2 h-2 overflow-hidden rounded bg-slate-200"><div class="h-full bg-brand-600" style="width:${total ? Math.round(done*100/total) : 0}%"></div></div><div class="mt-5 space-y-4">${roadmap.map((phase, pi) => `<section><h3 class="font-bold">${escapeHtml(phase.name)}</h3><p class="text-sm text-slate-600">${escapeHtml(phase.objective)}</p><ul>${phase.tasks.map((task, ti) => `<li id="roadmap-task-${pi}-${ti}"><label class="flex gap-2 py-1 text-sm"><input type="checkbox" ${task.done ? 'checked' : ''} onchange="window.toggleRoadmapTask('${id}',${pi},${ti})"><span>${escapeHtml(task.text)}</span></label>`).join('')}</ul><p class="text-xs text-slate-500">Outcome: ${escapeHtml(phase.outcome)}</p></section>`).join('')}</div></section>`; };
export const ImprovementView = i => `<section class="rounded-2xl border border-accent-500 bg-white p-6"><h2 class="text-xl font-bold">Improvement advice</h2><p class="mt-3"><b>Change:</b> ${escapeHtml(i.whatToChange)}</p><p><b>Why:</b> ${escapeHtml(i.why)}</p><div class="mt-3 grid gap-3 md:grid-cols-2"><div><b>Suggested features</b>${textList(i.suggestedFeatures)}</div><div><b>Technology changes</b>${textList(i.technologyChanges)}</div></div><p class="mt-3"><b>Scope:</b> ${escapeHtml(i.scopeRecommendation)}</p><p><b>Expected improvement:</b> ${escapeHtml(i.expectedImprovement)}</p></section>`;
export const DashboardView = saved => {
  if (!saved || !saved.length) {
    return `<section class="pt-28 pb-16 max-w-6xl mx-auto px-4 sm:px-6">
      <div class="flex justify-between items-center mb-6">
        <div>
          <h1 class="text-3xl font-extrabold text-slate-900">Student Project Dashboard</h1>
          <p class="text-sm text-slate-500 mt-1">Manage, build, and prepare defenses for your final-year projects.</p>
        </div>
        <a href="#generate" class="rounded-xl bg-brand-600 px-4 py-2 font-bold text-white text-sm hover:bg-brand-700">+ New Idea</a>
      </div>
      <div class="rounded-2xl border border-slate-200 bg-white p-12 text-center">
        <p class="text-lg font-semibold text-slate-700">No saved projects found.</p>
        <p class="text-sm text-slate-500 mt-2">Generate project ideas or browse recommendations to start building your portfolio.</p>
        <a href="#generate" class="mt-6 inline-block rounded-xl bg-brand-600 px-6 py-3 font-bold text-white text-sm hover:bg-brand-700">Generate Project Ideas</a>
      </div>
    </section>`;
  }

  return `<section class="pt-28 pb-16 max-w-6xl mx-auto px-4 sm:px-6">
    <div class="flex flex-wrap justify-between items-center gap-4 mb-8">
      <div>
        <h1 class="text-3xl font-extrabold text-slate-900">Student Project Dashboard</h1>
        <p class="text-sm text-slate-500 mt-1">Active projects, implementation roadmaps, evaluation scores, and viva prep.</p>
      </div>
      <div class="flex gap-3">
        <a href="#compare" class="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50">Compare Projects</a>
        <a href="#generate" class="rounded-xl bg-brand-600 px-4 py-2 text-sm font-bold text-white hover:bg-brand-700">+ New Idea</a>
      </div>
    </div>

    <div class="grid gap-6 md:grid-cols-2">
      ${saved.map(p => {
        const roadmap = p.roadmap || [];
        const tasks = roadmap.flatMap((phase, pi) => (phase.tasks || []).map((task, ti) => ({ ...task, pi, ti, phase: phase.name })));
        const doneCount = tasks.filter(t => t.done).length;
        const totalTasks = tasks.length;
        const progressPct = totalTasks > 0 ? Math.round((doneCount * 100) / totalTasks) : 0;
        const nextTask = tasks.find(t => !t.done);
        const currentPhase = nextTask?.phase || (totalTasks > 0 ? 'Completed' : 'Planning');
        const evalScore = p.evaluation?.overallScore ?? p.finalYearSuitabilityScore ?? p.feasibilityScore ?? '—';

        return `<article class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm flex flex-col justify-between hover:border-slate-300 transition-all">
          <div>
            <div class="flex justify-between items-start gap-3">
              <div>
                <span class="text-xs font-bold text-brand-600 uppercase tracking-wider">${escapeHtml(p.domain || 'General')} · ${escapeHtml(p.difficulty || 'Moderate')}</span>
                <h2 class="text-xl font-extrabold text-slate-900 mt-1">${escapeHtml(p.title)}</h2>
              </div>
              <div class="rounded-xl border border-brand-100 bg-brand-50 px-3 py-1.5 text-center shrink-0">
                <span class="text-[10px] font-bold uppercase text-brand-700 block">Score</span>
                <span class="text-lg font-extrabold text-brand-600">${escapeHtml(evalScore)}/100</span>
              </div>
            </div>
            <p class="mt-2 text-sm text-slate-600 line-clamp-2">${escapeHtml(p.shortDescription || '')}</p>

            <div class="mt-4 rounded-xl bg-slate-50 border border-slate-100 p-3.5">
              <div class="flex justify-between items-center text-xs text-slate-600 mb-1.5">
                <span class="font-bold">Progress: ${doneCount}/${totalTasks} Tasks (${progressPct}%)</span>
                <span class="font-semibold text-slate-500">Phase: ${escapeHtml(currentPhase)}</span>
              </div>
              <div class="h-2 w-full overflow-hidden rounded-full bg-slate-200">
                <div class="h-full bg-brand-600 rounded-full transition-all" style="width: ${progressPct}%"></div>
              </div>
              ${nextTask ? `<p class="mt-2 text-xs text-slate-700 truncate"><span class="font-bold text-slate-900">Next:</span> ${escapeHtml(nextTask.text)}</p>` : ''}
            </div>
          </div>

          <div class="mt-6 pt-4 border-t border-slate-100 flex flex-wrap gap-2 items-center justify-between">
            <div class="flex flex-wrap gap-2">
              <button onclick="window.openProjectById('${p.id}')" class="rounded-lg bg-slate-900 px-3 py-1.5 text-xs font-bold text-white hover:bg-slate-800">Details</button>
              <button onclick="window.continueBuildingProject('${p.id}')" class="rounded-lg bg-brand-600 px-3 py-1.5 text-xs font-bold text-white hover:bg-brand-700">Continue</button>
              <button onclick="window.openMentorById('${p.id}')" class="rounded-lg border border-slate-300 bg-white px-2.5 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-50">Mentor</button>
              <button onclick="window.openPresentationById('${p.id}')" class="rounded-lg border border-indigo-200 bg-indigo-50 px-2.5 py-1.5 text-xs font-semibold text-indigo-700 hover:bg-indigo-100">Presentation</button>
              <button onclick="window.openVivaById('${p.id}')" class="rounded-lg border border-purple-200 bg-purple-50 px-2.5 py-1.5 text-xs font-semibold text-purple-700 hover:bg-purple-100">Viva</button>
            </div>
            <div class="flex gap-2">
              <button onclick="window.toggleCompareProject('${p.id}')" class="text-xs text-slate-500 hover:text-slate-800 font-semibold" title="Toggle Compare">Compare</button>
              <button onclick="window.deleteProject('${p.id}')" class="text-xs text-rose-600 hover:text-rose-800 font-semibold" title="Delete from Dashboard">Delete</button>
            </div>
          </div>
        </article>`;
      }).join('')}
    </div>
  </section>`;
};
export const CompareView = projects => { if (projects.length < 2) return `<section class="pt-28 max-w-4xl mx-auto px-4"><h1 class="text-3xl font-bold">Compare projects</h1><p class="mt-4">Add at least two projects from Project Details to compare them.</p></section>`; const best=[...projects].sort((a,b)=>((b.evaluation?.overallScore||0)+b.feasibilityScore+b.innovationScore)-((a.evaluation?.overallScore||0)+a.feasibilityScore+a.innovationScore))[0]; return `<section class="pt-28 pb-16 max-w-6xl mx-auto px-4"><h1 class="text-3xl font-bold">Compare projects</h1><div class="mt-5 overflow-x-auto"><table class="w-full bg-white text-sm"><thead><tr><th class="p-3 text-left">Measure</th>${projects.map(p=>`<th class="p-3 text-left">${escapeHtml(p.title)}</th>`).join('')}</tr></thead><tbody>${[['Overall score',p=>p.evaluation?.overallScore||'—'],['Feasibility',p=>p.feasibilityScore],['Innovation',p=>p.innovationScore],['Technical depth',p=>p.evaluation?.technicalDepthScore||'—'],['Final-year suitability',p=>p.evaluation?.finalYearSuitabilityScore||p.finalYearSuitabilityScore],['Scope fit',p=>p.evaluation?.scopeFitScore||'—'],['Difficulty',p=>p.difficulty],['Technology stack',p=>p.techStack.join(', ')],['Estimated complexity',p=>p.estimatedScope]].map(([l,f])=>`<tr class="border-t"><th class="p-3 text-left">${l}</th>${projects.map(p=>`<td class="p-3">${escapeHtml(f(p))}</td>`).join('')}</tr>`).join('')}</tbody></table></div><section class="mt-6 rounded-2xl bg-brand-50 p-5"><h2 class="font-bold">Best Overall Choice</h2><p class="mt-2"><b>${escapeHtml(best.title)}</b> has the strongest combined feasibility, innovation, and available evaluation score.</p></section></section>`; };

const mentorMessage = message => `<article class="rounded-xl p-3 text-sm ${message.role === 'user' ? 'bg-brand-50' : 'bg-slate-100'}"><b>${message.role === 'user' ? 'You' : 'Mentor'}</b><p class="mt-1 whitespace-pre-wrap">${escapeHtml(message.content)}</p>${message.nextSteps ? `<div class="mt-2"><b>Next steps</b>${textList(message.nextSteps)}</div>` : ''}${message.relevantRoadmapTasks?.length ? `<div class="mt-2"><b>Relevant roadmap tasks</b>${textList(message.relevantRoadmapTasks)}</div>` : ''}${message.warnings?.length ? `<div class="mt-2"><b>Warnings</b>${textList(message.warnings)}</div>` : ''}</article>`;
export const MentorView = ({ project, messages = [], operation = {} }) => `<section class="pt-28 pb-16 max-w-4xl mx-auto px-4"><a href="#project/${encodeURIComponent(project.id)}" class="text-sm font-bold text-brand-600">← Back to project</a><header class="mt-4 rounded-2xl bg-slate-900 p-6 text-white"><p class="text-sm text-brand-300">Context-aware AI mentor</p><h1 class="text-2xl font-extrabold">${escapeHtml(project.title)}</h1><p class="mt-2 text-sm text-slate-300">Uses your project, blueprint, roadmap, and current progress.</p></header><div class="mt-5 rounded-2xl border bg-white p-5"><div class="min-h-40 space-y-4" aria-live="polite">${messages.length ? messages.map(mentorMessage).join('') : '<p class="text-sm text-slate-500">Ask a question to get tailored guidance.</p>'}</div><div class="mt-4 flex flex-wrap gap-2">${['How do I start?','What should I build first?','Help me with the backend','How can I improve this project?','Prepare me for viva'].map(q=>`<button onclick="window.setMentorQuestion('${q}')" class="rounded-full border px-3 py-1 text-xs">${q}</button>`).join('')}</div><label class="mt-4 block text-sm font-bold" for="mentor-question">Ask your mentor</label><textarea id="mentor-question" maxlength="2000" class="mt-1 w-full rounded-xl border p-3" placeholder="Describe where you are stuck or what you want to plan."></textarea><div class="mt-3 flex gap-3"><button onclick="window.sendMentorQuestion()" class="rounded-xl bg-brand-600 px-4 py-2 font-bold text-white">Send</button><button onclick="window.clearMentorConversation()" class="rounded-xl border px-4 py-2">Clear conversation</button></div>${operation.loading?'<p class="mt-3 text-sm" role="status">Mentor is thinking…</p>':operation.error?`<p class="mt-3 text-sm text-red-700" role="alert">${escapeHtml(operation.error)} <button onclick="window.retryMentorQuestion()" class="font-bold underline">Retry</button></p>`:''}</div></section>`;
export const MentorUnavailableView = () => `<section class="pt-28 pb-16 max-w-2xl mx-auto px-4"><div class="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h1 class="text-2xl font-extrabold">Selected project context is unavailable</h1><p class="mt-3 text-sm text-slate-700">Please reopen the project from your recommendations or saved projects before using the Mentor.</p><a href="#dashboard" class="mt-5 inline-block rounded-xl bg-brand-600 px-4 py-2 font-bold text-white">Open saved projects</a></div></section>`;
